name: Release to Nuget

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    branches: [master]

env:
  TAG_NAME: ${{ github.event.release.tag_name }}
  PROJECT_PATH: ./RestApiClient.NetStandard
  ARTIFACT_NAME: TheProcessE.RestClient
  PACKAGE_RELEASE_NOTES_URL: https://github.com/PascalBenstrong/Rest-Client/releases/tag/
  PACKAGE_OUTPUT_DIRECTORY: ${{ github.workspace }}\output
  NUGET_SOURCE_URL: "https://api.nuget.org/v3/index.json"
  NUGET_AUTH_TOKEN: ${{secrets.NUGET_AUTH_TOKEN}}

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "5.0.x"

      - name: Run Tests
        run: dotnet test

      - name: Build Project
        run: dotnet build ${{env.PROJECT_PATH}} -c Release --no-restore

      - name: Get Version
        id: version
        uses: battila7/get-version-action@v2

      - name: Create Nuget Package
        run: dotnet pack ${{env.PROJECT_PATH}} -c Release --no-restore --include-symbols --output ${{env.PACKAGE_OUTPUT_DIRECTORY}} -p:PackageVersion=${{ steps.version.outputs.version-without-v }} -p:PackageReleaseNotes="See ${{env.PACKAGE_RELEASE_NOTES_URL}}${{ env.TAG_NAME }}"

      - name: Archive Nuget Package
        uses: actions/upload-artifact@v1
        with:
          name: ${{env.ARTIFACT_NAME}}.${{ env.TAG_NAME }}.nupkg
          path: ${{env.PACKAGE_OUTPUT_DIRECTORY}}\*.nupkg

      - name: Push Package
        run: dotnet nuget push ${{env.PACKAGE_OUTPUT_DIRECTORY}}\*.nupkg -k ${{env.NUGET_AUTH_TOKEN}} -s ${{env.NUGET_SOURCE_URL}}
